ham_addresses = ['rssfeeds@spamassassin.taint.org', 'cwg-exmh@deepeddy.com', 'rssfeeds@example.com', 'yyyy@spamassassin.taint.org',
 'darren.kenny@sun.com', 'david&tomgardner@fooladvisor.com"<subscriber@fooladvisor.com', 'pudge@perl.org', 'stevek@stevek.com', 
 'bronger@users.sourceforge.net', 'prlawrence@lehigh.edu', 'angles@aminvestments.com', 'hyatt@mozilla', 'skyhawk@redbrick.dcu.ie', 
 'johngay@eircom.net', 'bootsys@eircom.net', 'haldevore@acm.org', 'lars@unet.net.ph', 'ross@willow.seitz.com', 'hello@ianbell.com', 
 'anders.holm@elivefree.net', 'garym@canada.com', 'matthias@rpmforge.net', 'beberg@mithral.com', 'owen@permafrost.net', 'tomwhore@slack.net', 
 'nobody@dogma.slashnull.org', 'rah@shipwright.com', 'jeremy@alum.mit.edu', 'gojomo@usa.net', 'robert.chambers@baesystems.com', 
 'mailman-owner@lists.sourceforge.net', 'niall@linux.ie', 'tbridge@vianetworks.ie', 'admin@wexoe.dk', 'timc@2ubh.com', 'brian.odonoghue@kbs.ie',
  'champion@handango.com', 'rhn-admin@rhn.spamassassin.taint.org', 'tim.one@comcast.net', 'ejw@cse.ucsc.edu', 'damian.osullivan@bcs.ie', 
  'geege@barrera.org', 'fork-admin@xent.com', 'felicity@kluge.net', 'dwalsh@blather.net', 'brendan.halpin@ul.ie', 'msquadrat.nospamplease@gmx.net', 
  'laurie@primal.ucdavis.edu', 'thosstew@aol.com', 'gregory.mcrandal@fineos.com', 'mailinglists@websitemanagers.com.au', 'pelle@neubia.com', 
  'bugzilla-daemon@hughes-family.org', 'pmatilai@welho.com', 'cdale@techmonkeys.net', 'foxsportsflash@mailings.foxsports.com', 'johnhall@evergo.net', 
  'graham.smith@it-tallaght.ie', 'mailto:cj@nologic.org', 'skip@pobox.com', 'signa@birch.net', 'chad@cloudmark.com', 'colin@easydns.com', 
  'sven@dmv.com', 'online#3.20314.4f-dcw3gqtnlgtxgdrr.1@newsletter.online.com', 'zeek@sparklehouse.com', 'neugens@libero.it', 'harri.haataja@cs.helsinki.fi',
   'online#3.19965.2a-726zgp3ui7kto9rr.1@newsletter.online.com', 'gkm@petting-zoo.net', 'online#3.20340.74-k8ccgc95n6xnp9rr.1@newsletter.online.com', 
   'ville.skytta@iki.fi', 'hauns_froehlingsdorf@infinetivity.com', 'iiu-admin@taint.org', 'emailharvest@email.com', 
   'online#3.20504.8b-aopnlj_w_jjk69rr.1@newsletter.online.com', 'nickm@go2.ie', 'deafbox@hotmail.com', 'bitbitch@magnesium.net',
    'dbr@greenhydrant.com', 'colm@tuatha.org', 'coy.krill@verizon.net', 'dave@davegreen.co.uk', 'kevin+dated+1029676051.792347@ie.suberic.net',
     'fork_list@hotmail.com', 'yyyy@example.com', 'online#3.19976.19-zxcpgoyroraemrrr.1@newsletter.online.com', 'dumas@centre-cired.fr', 
     'plinehan@yahoo.com', 'sdw@lig.net', 'jamesr@best.com', 'online#3.19856.0b-j216gbvtducsysrr.1@newsletter.online.com', 'yyyyason@users.sourceforge.net', 
     'lgonze@panix.com', 'kevinc@doink.com', 'xxxxxxx@xxxxxxxxx.com', 'gerry.carr@eware.com', 'peter.peltonen@iki.fi', 'harley@argote.ch', 'zamoose610@yahoo.com', 'postmaster@jpci.net',
'deafbox@hotmail.com', 'eugen@leitl.org', 'fork_list@hotmail.com', 'johnhall@evergo.net', 'rssfeeds@example.com', 'reinke@e-softinc.com', 'haldevore@acm.org', 
'eh@mad.scientist.com', 'bugzilla-daemon@hughes-family.org', 'reg@dwf.com', 'yyyy@spamassassin.taint.org', 'horkana@tcd.ie', 'neugens@libero.it', 'valen@tuatha.org', 'ken.coar@golux.com',
 'pudge@perl.org', 'update@list.theregister.co.uk', 'rbfar@ebuilt.com', 'fork-admin@xent.com', 'jbeck@eng.sun.com', 'dgw-lists@birches.org', 'javier@linkcreations.com.mx', 'signa@birch.net', 
 'monty@roscom.com', 'jpr5@darkridge.com', 'mailto:noc@internap.com', 'andrew@internap.com', 'rssfeeds@spamassassin.taint.org', 'gward@python.net', 'lance_tt@bellsouth.net', 
 'chris@noskillz.com', 'welch@panasas.com', 'harley@argote.ch', 'pmatilai@welho.com', 'tomwhore@slack.net', 'brian.odonoghue@kbs.ie', 'bill@whump.com', 'matthias@rpmforge.net', 
 'ville.skytta@iki.fi', 'nnt@silver.lyris.net', 'jamesr@best.com', 'rah@shipwright.com', 'dave@farber.net', 'garym@canada.com', 'felicity@kluge.net', 'dandanielle@mindspring.com',
  'barry@python.org', 'distribution@ximian.com', 'angles@aminvestments.com', 'lgonze@panix.com', 'dermot.daly@itsmobile.com', 'online#3.20481.4a-uljjgrvqntkdnrrr.1@newsletter.online.com',
   'khare@alumni.caltech.edu', 'mailer-daemon@prodigy.net', 'online#3.20284.fc-lmywlax_4cin49rr.1@newsletter.online.com', 'tony@linuxworks.com.au', 'b.hunt@emuse-tech.com', 
   'stephen_reilly@dell.com', 'ralf@camperquake.de', 'zzzz@example.com', 'ben@benhammersley.com', 'chris.higgins@hts.horizon.ie', 'crist.clark@attbi.com', 'network<replies@oracleeblast.com',
    'robinderbains@shaw.ca', 'damien.morton@acm.org', 'mailto:damien.morton@acm.org', 'phil@redbrick.dcu.ie', 'linux-announce-request@senator-bedfellow.mit.edu', 'ooplist@bruceeckel.com', 
    'fred@bytesforall.org', 'gazette@ssc.com', 'lev@codenetic.net', 'kra@monkey.org', 'rick@linuxmafia.com', 'rlfrank@paradigm-omega.com', 'gbolcer@endeavors.com', 'padraig.brady@corvil.com', 
    'subscriptions@lockergnome.com', 'tony@svanstrom.com', 'guterman@mediaunspun.imakenews.net', 'thosstew@aol.com', 'deccy@csn.ul.ie', 'rgilmanhunt@hotp.com', 'paul.askins@analog.com', 
    'online#3.20516.fc-lmywlax_4cin49rr.1@newsletter.online.com', 'geege@barrera.org', 'garym@maya.dyndns.org', 'cwg-exmh@deepeddy.com', 'kilroy@kamakiriad.com', 'beberg@mithral.com', 
    'online#3.20777.51-8j4zge1uu7_vxsrr.1@newsletter.online.com', 'rod@arsecandle.org', 'owen@permafrost.net', 'dag@newtech.fi', 'axel.thimm@physik.fu-berlin.de', 'bob@proulx.com', 
    'elias@cse.ucsc.edu', 'online#3.19690.d9-is5vl-4ybsbwq9rr.1@newsletter.online.com', 'maxdunn@siliconpublishing.com', 'newsletters@buy4now.ie', 
    'online#3.20292.e9-wy20laqkodqzlsrr.1@newsletter.online.com', 'online#3.20216.56-c0axgilv9ymfp9rr.1@newsletter.online.com', 'aeriksson@fastmail.fm', 'noghri@nauticom.net', 'nas@python.ca', 'andy@r2-dvd.org']

